###
- name: Jenkins configure
  hosts: appserver
  vars_files:
    - vars.yml
  become: true
  become_user: root
  tasks:
    - name: Create user jenkins
      user:
        name: "{{ jenkins_user }}"
        home: "{{ jenkins_home }}"
    - name: Install java
      yum:
        name: "{{ package_java }}"
        state: present
    - name: Get jenkins.war 
      copy:
        src: "{{ jenkins_url }}"
        dest: "{{jenkins_war_path }}"
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
    - name: Copy jenkins service
      template:
        src: jenkins.service.j2
        dest: /etc/systemd/system/jenkins.service
    - name: Reload systemd and jenkins start
      systemd:
        daemon_reload: yes
        name: jenkins
        enabled: yes
        state: started
    - name: Wait for Jenkins start
      wait_for:
        host=localhost
        port=8080
        delay=30
        timeout=60   
###
- name: Install and configure httpd
  hosts: webserver
  vars_files:
    - vars.yml
  become: true
  become_user: root
  tasks:
    - name: Install httpd
      yum: 
        name: "{{ package_httpd }}" 
        state: latest
    - name: configure httpd
      template:
        src: jenkins.conf.j2
        dest: /etc/httpd/conf.d/jenkins.conf
    - name: httpd start and enable
      systemd:
        name: httpd
        enabled: yes
        state: started
    - name: Wait for httpd start
      wait_for:
        host=localhost
        port=80
        delay=10
        timeout=60  

