# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.box = "sbeliakou/centos-7.5-x86_64-minimal"

  config.vm.define "webserver" do |httpd|
    httpd.vm.provider :"virtualbox" do |virt|
      virt.name = "httpd-CM"
      virt.memory = "1024"
    end
    httpd.vm.hostname = "apache"
    httpd.vm.network "private_network", ip: "192.168.1.20"
  end
  
  config.vm.define "appserver" do |jenkins|
    jenkins.vm.provider :"virtualbox" do |virt|
      virt.name = "jenkins-CM"
      virt.memory = "2048"
    end
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.1.30"
  end
end
