---
# tasks file for jenkins
#
- name: Create user group jenkins
  group:
    name: "{{ jenkins_group }}"
    state: present
    gid: "{{ jenkins_guid }}"
  become: yes

- name: Create user jenkins
  user:
    name: "{{ jenkins_user }}"
    home: "{{ jenkins_home }}"
    group: "{{ jenkins_group }}"
    uid: "{{ jenkins_uid }}"
  become: yes

- name: Get jenkins.war from local
  copy:
    src: jenkins.war
    dest: "{{jenkins_war_path }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
  become: yes
  notify:
    - "restart"
    - "test_health"
  tags:
    - never


- name: Get jenkins.war
  get_url:
    url: "{{ jenkins_url }}"
    dest: "{{jenkins_war_path }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
  become: yes
  notify:
    - "restart"
    - "test_health"
  tags:
    - url

- name: Copy jenkins service
  template:
    src: jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service
  become: yes
  notify:
    - systemd_daemon_reload
    - "restart"
    - "test_health"

- name: Service is enable
  systemd:
    name: jenkins
    enabled: yes
    state: started
  become: yes
  notify:
    - "test_health"


