---
# tasks file for java
#
- name: Install java
  yum:
    name: "java-{{ jdk_major_version }}-openjdk"
    state: present
  become: yes

- name: Verifies java installation
  shell: "java -version 2>&1 | grep {{ jdk_major_version }}"
  register: java_version_info
  changed_when: False 

- name: Ensure Facts Directory Exists
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory
  become: yes
