###
- name: local action 
  hosts: localhost
  vars:
    ssh_key_path: "{{ user_key }}.pem"
    user_key: devops

  tasks:
  - name: Create ssh key for user
    command: "ssh-keygen -t rsa -f {{ ssh_key_path }} -N"
    args:
      creates: "{{ ssh_key_path }}"
  - name: Ensure Ansible Facts Dir Exists
    file:
      path: /etc/ansible/facts.d
      state: directory
      recurse: yes
    become: yes

###
- name: Create devops user
  hosts:
    - appserver
    - webserver
  roles:
    - devops_user

###
- name: Install Jenkins
  hosts:
    - appserver
  pre_tasks:
    - debug: msg="will work first" 
  roles:
    - jenkins 
  tasks:
    - debug: msg="will work after roles" 
  post_tasks:
    - debug: msg="will work at the end"
###
- name: Install httpd
  hosts:
    - webserver
  pre_tasks:
    - debug: msg="will work first"
  roles:
    - { role: httpd, app_ip: "{{ hostvars[groups['appserver'][0]]['ansible_host'] }}" }
  tasks:
    - debug: msg="will work after roles"
  post_tasks:
    - debug: msg="will work at the end"



