- name: local actions
  hosts: localhost
  tasks:
  - name: Create ssh key for user
    command: "ssh-keygen -t rsa -f {{ ansible_ssh_private_key_file }} -N ''"
    args:
      creates: "{{ ansible_ssh_private_key_file }}"

