- name: Install httpd
  hosts:
    - webserver
  pre_tasks:
    - debug:
        msg: "HOST: {{ inventory_hostname }} | {{ ansible_host }}"
  roles:
    - { role: httpd, app_ip: "{{ hostvars[groups['appserver'][0]]['ansible_host'] }}" }
    - role: sanity_test 
      vars:
        n_proc: "httpd" 
        u_proc: "root"
        p_proc: 80 
        url: "http://127.0.0.1:80/login" 
        c_r_str: "Jenkins" 
        s_r_str: "Jenkins" 
      tags: 
      - sanity

