- name: Install Jenkins
  hosts:
    - appserver
  pre_tasks:
    - debug:
        msg: "HOST: {{ inventory_hostname }} | {{ ansible_host }}"
  roles:
    - jenkins
    - role: sanity_test 
      vars:
        n_proc: "jenkins" 
        u_proc: "jenkins" 
        p_proc: "8080" 
        url: "http://127.0.0.1:8080/login" 
        c_r_str: "Jenkins" 
        s_r_str: "Jenkins" 
      tags: 
      - sanity 

